// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include "stack/include/ember.h"
#include CONFIGURATION_HEADER
#include EMBER_AF_API_COMMAND_INTERPRETER2

void emberPrintCommandTable(void);
void emberGpdAfCliChannelReq(void);
void emberGpdAfCliCommReq(void);
void emberGpdAfCliNodeInfo(void);
void emberGpdAfCliNodeSetAutoComm(void);
void emberGpdAfCliNodeSetAddr(void);
void emberGpdAfCliNodeSetBiDirParam(void);
void emberGpdAfCliNodeSetChannel(void);
void emberGpdAfCliNodeSetSecFc(void);
void emberGpdAfCliNodeSetSecKey(void);
void emberGpdAfCliNodeSetSecKeyType(void);
void emberGpdAfCliNodeSetSecLevel(void);
static EmberCommandEntry emberCommandNodeTable[] = {
  emberCommandEntryActionWithDetails("channel-req", emberGpdAfCliChannelReq, "", "", NULL),
  emberCommandEntryActionWithDetails("comm", emberGpdAfCliCommReq, "u", "", NULL),
  emberCommandEntryActionWithDetails("info", emberGpdAfCliNodeInfo, "", "", NULL),
  emberCommandEntryActionWithDetails("set-ac", emberGpdAfCliNodeSetAutoComm, "u", "", NULL),
  emberCommandEntryActionWithDetails("set-addr", emberGpdAfCliNodeSetAddr, "u*", "", NULL),
  emberCommandEntryActionWithDetails("set-bidir-param", emberGpdAfCliNodeSetBiDirParam, "uuu", "", NULL),
  emberCommandEntryActionWithDetails("set-channel", emberGpdAfCliNodeSetChannel, "u", "", NULL),
  emberCommandEntryActionWithDetails("set-sec-fc", emberGpdAfCliNodeSetSecFc, "w", "", NULL),
  emberCommandEntryActionWithDetails("set-sec-key", emberGpdAfCliNodeSetSecKey, "b", "", NULL),
  emberCommandEntryActionWithDetails("set-sec-key-type", emberGpdAfCliNodeSetSecKeyType, "u", "", NULL),
  emberCommandEntryActionWithDetails("set-sec-level", emberGpdAfCliNodeSetSecLevel, "u", "", NULL),
  emberCommandEntryTerminator(),
};
void emberGpdAfCliSendGpdf(void);
void emberGpdAfCliSensorReport(void);
void emberGpdAfCliSensorSleep(void);
static EmberCommandEntry emberCommandSensorTable[] = {
  emberCommandEntryActionWithDetails("report", emberGpdAfCliSensorReport, "", "", NULL),
  emberCommandEntryActionWithDetails("sleep", emberGpdAfCliSensorSleep, "", "", NULL),
  emberCommandEntryTerminator(),
};
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("help", emberPrintCommandTable, "", "", NULL),
  emberCommandEntrySubMenu("node", emberCommandNodeTable, ""),
  emberCommandEntryActionWithDetails("send-gpdf", emberGpdAfCliSendGpdf, "ub", "", NULL),
  emberCommandEntrySubMenu("sensor", emberCommandSensorTable, ""),
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
