// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include "gpd-components-common.h"
#include PLATFORM_HEADER
#include "hal/hal.h"
#include CONFIGURATION_HEADER
#include EMBER_AF_API_NVM3


/** @brief Called to get the application information payload from application. This callback
 *         helps application to filled up the application specefic application information
 *         that gets transmitted.
 *
 * @param messagePayload The pointer for the user to fillup.
 * @param maxLength maximum length.
 * @param last indicates the present application description packet is the last one.
 * Ver.: always
 *
 * @return the length writen by application.
 */
uint8_t emberGpdAfPluginGetApplicationDescriptionCallback(uint8_t * messagePayload,
                                                          uint8_t maxLength,
                                                          bool * last)
{
  // This is an example of how to fill up an occupany sensor report as application description
  // The following is a single report descriptor for the occupancy attribute.
  uint8_t appDesc[13] = {0x01, 0x01, 0x00, 0x00, 0x07, 0x08, 0x06, 0x04, 0x00, 0x00, 0x18, 0x10, 0x00};
  memcpy (messagePayload, appDesc, sizeof(appDesc));
  *last = true;
  return sizeof(appDesc);
}


/** @brief This is called by framework to receive a contact status in case of generic switch
 *         info during commissioning request.
 *
 * @return a 8bit switch contact status.
 */
uint8_t emberGpdAfPluginGetSwitchContactStutusCallback(void)
{
  return 0;
}


/** @brief This is called by framework to get a random number. User should implement it appropriately
 * depending on the random number generation in the project.
 *
 * @return a 32bit random number.
 */
uint32_t emberGpdAfPluginGetRandomCallback(void)
{
  volatile uint32_t randomValue;
  return randomValue;
}


/** @brief This is called by framework to get the IEEE (EUI64) address of the GPD.
 * Typically GPD application may have the IEEE address for each of the GPD programmed at a different
 * location or storage, so the framework obtains the address through this callback.
 *
 * @param eui pointer to collect the ieee
 * @param gpdEndpoint pointer to collect gpd endpoint
 */
void emberGpdAfPluginGetGpdIeeeCallback(uint8_t *eui,
                                        uint8_t *gpdEndpoint)
{
  uint8_t ieee[] = EMBER_AF_PLUGIN_APPS_IEEE;
  memcpy(eui, ieee, EMBER_GPD_EUI64_SIZE);
  *gpdEndpoint = EMBER_AF_PLUGIN_APPS_GPD_ENDPOINT;
}



/**
 * @brief Called whenever the radio is powered on.
 */
void halRadioPowerUpHandler(void)
{
}


/**
 * @brief Called whenever the radio is powered off.
 */
void halRadioPowerDownHandler(void)
{
}


/**
 * @brief Called whenever the microcontroller enters/exits a idle/sleep mode
 *
 * @param enter        True if entering idle/sleep, False if exiting
 * @param sleepMode    Idle/sleep mode
 */
void halSleepCallback(boolean enter, SleepModes sleepMode)
{
}


// The NVM3 Callback function.
void halNvm3Callback(Ecode_t status)
{
  // NVM3 does error handling internally, but this callback is included
  // in case the application requires any custom error handling.
}


